# Generated by Django 4.0.6 on 2022-09-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedidos',
        ),
    ]
