# Generated by Django 4.0.6 on 2022-09-07 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_alter_receita_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='preco',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_total', models.FloatField()),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.receita')),
            ],
        ),
    ]
