# Generated by Django 4.0.6 on 2022-09-08 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0006_alter_receita_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='comida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='receitas.receita'),
        ),
    ]
