# Generated by Django 4.0.6 on 2022-09-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0007_alter_pedidos_comida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='preco_total',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
